try{
    hello();
}catch(err){
    console.log(err);
}


// luego 

try{
    anotherFunction();
}catch{
    console.log('esto es un error');
}